server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location /api/ {
        proxy_pass https://vicaria-api.mateopavoni.com.ar/api/;
        proxy_set_header Host vicaria-api.mateopavoni.com.ar;
        proxy_ssl_server_name on;
    }

    # SPA: cualquier ruta que no exista como archivo cae en index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
